version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: braces
    versions:
    - 2.3.2
  - dependency-name: "@fullhuman/postcss-purgecss"
    versions:
    - 3.1.3
  - dependency-name: gulp-svgmin
    versions:
    - 3.0.0
  - dependency-name: gulp-rsync
    versions:
    - 0.0.9
