baseURL:                  "/"
languageCode:             "en-us"
title:                    "Flightdeck Go ðŸš€"

googleAnalytics:          UA-xxxxxx-xx

enableRobotsTXT:          true

disableRSS:               true
disableKinds:             ["section", "taxonomy", "taxonomyTerm", "RSS"]

privacy:
  googleAnalytics:
    anonymizeIP:          true
    respectDoNotTrack:    true
  twitter:
    enableDNT:            true
  youtube:
    privacyEnhanced:      true
