baseURL: "http://example.org/"
languageCode: en-us
title: 'Flightdeck: A Scaffold for Hugo'
params:
  description: >
    Flightdeck is a scaffold and starter project for Hugo that uses an opinionated modern front-end workflow.

# SEO Privacy
googleAnalytics: UX-xxxxxx-xx
enableRobotsTXT: true

disableRSS: true
disableKinds: ["section", "taxonomy", "taxonomyTerm", "RSS"]
disableHugoGeneratorInject: true

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
